//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/CrazyMelvinsShoppingEmporiumRESTfulServic" +
        "e.Models")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int custIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int custID {
            get {
                return this.custIDField;
            }
            set {
                if ((this.custIDField.Equals(value) != true)) {
                    this.custIDField = value;
                    this.RaisePropertyChanged("custID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/CrazyMelvinsShoppingEmporiumRESTfulServic" +
        "e.Models")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Cart[] CartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int custIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime orderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string poNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Cart[] Carts {
            get {
                return this.CartsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartsField, value) != true)) {
                    this.CartsField = value;
                    this.RaisePropertyChanged("Carts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int custID {
            get {
                return this.custIDField;
            }
            set {
                if ((this.custIDField.Equals(value) != true)) {
                    this.custIDField = value;
                    this.RaisePropertyChanged("custID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime orderDate {
            get {
                return this.orderDateField;
            }
            set {
                if ((this.orderDateField.Equals(value) != true)) {
                    this.orderDateField = value;
                    this.RaisePropertyChanged("orderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderID {
            get {
                return this.orderIDField;
            }
            set {
                if ((this.orderIDField.Equals(value) != true)) {
                    this.orderIDField = value;
                    this.RaisePropertyChanged("orderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poNumber {
            get {
                return this.poNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.poNumberField, value) != true)) {
                    this.poNumberField = value;
                    this.RaisePropertyChanged("poNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/CrazyMelvinsShoppingEmporiumRESTfulServic" +
        "e.Models")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderID {
            get {
                return this.orderIDField;
            }
            set {
                if ((this.orderIDField.Equals(value) != true)) {
                    this.orderIDField = value;
                    this.RaisePropertyChanged("orderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prodID {
            get {
                return this.prodIDField;
            }
            set {
                if ((this.prodIDField.Equals(value) != true)) {
                    this.prodIDField = value;
                    this.RaisePropertyChanged("prodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/CrazyMelvinsShoppingEmporiumRESTfulServic" +
        "e.Models")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Cart[] CartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool inStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double prodWeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Cart[] Carts {
            get {
                return this.CartsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartsField, value) != true)) {
                    this.CartsField = value;
                    this.RaisePropertyChanged("Carts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool inStock {
            get {
                return this.inStockField;
            }
            set {
                if ((this.inStockField.Equals(value) != true)) {
                    this.inStockField = value;
                    this.RaisePropertyChanged("inStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prodID {
            get {
                return this.prodIDField;
            }
            set {
                if ((this.prodIDField.Equals(value) != true)) {
                    this.prodIDField = value;
                    this.RaisePropertyChanged("prodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodName {
            get {
                return this.prodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.prodNameField, value) != true)) {
                    this.prodNameField = value;
                    this.RaisePropertyChanged("prodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double prodWeight {
            get {
                return this.prodWeightField;
            }
            set {
                if ((this.prodWeightField.Equals(value) != true)) {
                    this.prodWeightField = value;
                    this.RaisePropertyChanged("prodWeight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingEmporiumService.IShoppingEmporium")]
    public interface IShoppingEmporium {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/GetCustomerList", ReplyAction="http://tempuri.org/IShoppingEmporium/GetCustomerListResponse")]
        CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer[] GetCustomerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/GetCustomerList", ReplyAction="http://tempuri.org/IShoppingEmporium/GetCustomerListResponse")]
        System.Threading.Tasks.Task<CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer[]> GetCustomerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/GetCustomer", ReplyAction="http://tempuri.org/IShoppingEmporium/GetCustomerResponse")]
        CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer GetCustomer(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/GetCustomer", ReplyAction="http://tempuri.org/IShoppingEmporium/GetCustomerResponse")]
        System.Threading.Tasks.Task<CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer> GetCustomerAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/AddCustomer", ReplyAction="http://tempuri.org/IShoppingEmporium/AddCustomerResponse")]
        void AddCustomer(CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/AddCustomer", ReplyAction="http://tempuri.org/IShoppingEmporium/AddCustomerResponse")]
        System.Threading.Tasks.Task AddCustomerAsync(CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/UpdateCustomer", ReplyAction="http://tempuri.org/IShoppingEmporium/UpdateCustomerResponse")]
        void UpdateCustomer(CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/UpdateCustomer", ReplyAction="http://tempuri.org/IShoppingEmporium/UpdateCustomerResponse")]
        System.Threading.Tasks.Task UpdateCustomerAsync(CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/DeleteCustomer", ReplyAction="http://tempuri.org/IShoppingEmporium/DeleteCustomerResponse")]
        void DeleteCustomer(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingEmporium/DeleteCustomer", ReplyAction="http://tempuri.org/IShoppingEmporium/DeleteCustomerResponse")]
        System.Threading.Tasks.Task DeleteCustomerAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShoppingEmporiumChannel : CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.IShoppingEmporium, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoppingEmporiumClient : System.ServiceModel.ClientBase<CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.IShoppingEmporium>, CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.IShoppingEmporium {
        
        public ShoppingEmporiumClient() {
        }
        
        public ShoppingEmporiumClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoppingEmporiumClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingEmporiumClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingEmporiumClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer[] GetCustomerList() {
            return base.Channel.GetCustomerList();
        }
        
        public System.Threading.Tasks.Task<CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer[]> GetCustomerListAsync() {
            return base.Channel.GetCustomerListAsync();
        }
        
        public CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer GetCustomer(string id) {
            return base.Channel.GetCustomer(id);
        }
        
        public System.Threading.Tasks.Task<CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer> GetCustomerAsync(string id) {
            return base.Channel.GetCustomerAsync(id);
        }
        
        public void AddCustomer(CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer customer) {
            base.Channel.AddCustomer(customer);
        }
        
        public System.Threading.Tasks.Task AddCustomerAsync(CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer customer) {
            return base.Channel.AddCustomerAsync(customer);
        }
        
        public void UpdateCustomer(CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer customer) {
            base.Channel.UpdateCustomer(customer);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerAsync(CrazyMelvinsShoppingEmporiumRESTfulService.Tests.ShoppingEmporiumService.Customer customer) {
            return base.Channel.UpdateCustomerAsync(customer);
        }
        
        public void DeleteCustomer(string id) {
            base.Channel.DeleteCustomer(id);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerAsync(string id) {
            return base.Channel.DeleteCustomerAsync(id);
        }
    }
}
